//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalChallenge_BasketballTeamApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalChallenge_BasketballTeamDBEntities : DbContext
    {
        public FinalChallenge_BasketballTeamDBEntities()
            : base("name=FinalChallenge_BasketballTeamDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fixture> Fixtures { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
    }
}
